/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "media",
  theme: {
    extend: {
      colors: {
        textPrimary: "var(--text-primary)",
        textSecondary: "var(--text-secondary)",
        textThird: "var(--text-third)",
        textFourth: "var(--text-fourth)",
        textFifth: "var(--text-fifth)",
        textBlack: "var(--text-black)",
        textDanger: "var(--text-danger)",
        button: {
          primary: "var(--button-primary)",
          secondary: "var(--button-secondary)",
        },
        borderPrimary: "var(--border-primary)",
        bgPrimary: "var(--bg-primary)",
        bgSecondary: "var(--bg-secondary)",
        bgThird: "var(--bg-third)",
        bgFourth: "var(--bg-fourth)",
        statusSuccessBg: "var(--status-success-bg)",
        statusSuccessText: "var(--status-success-text)",
        statusDangerBg: "var(--status-danger-bg)",
        statusDangerText: "var(--status-danger-text)",
        accentStar: "var(--accent-star)",
        skeletonBase: "var(--skeleton-base)",
        infoBg: "var(--info-bg)",
        infoBorder: "var(--info-border)",
        highlightBg: "var(--highlight-bg)",
        highlightBorder: "var(--highlight-border)",
        highlightText: "var(--highlight-text)",
        warningBg: "var(--warning-bg)",
        warningBorder: "var(--warning-border)",
        warningText: "var(--warning-text)",
        accentBlue: "var(--accent-blue)",
      },
    },
  },
  plugins: [],
};
